In [137]:
import numpy as np
import pandas as pd
from numpy.random import shuffle
from numpy.random import Generator as gen 
from numpy.random import PCG64 as pcg


In [138]:
np.set_printoptions(suppress=True, linewidth=100, precision=2)

# Importing data , analyse and preprocess by Donald Programmeur

In [139]:
raw_data = np.genfromtxt('data/loan-data.csv', delimiter=";", skip_header = 1, autostrip = True, encoding = "cp855")
raw_data

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

# Checking data

In [140]:
np.isnan(raw_data).sum()

88005

In [141]:
temporary_mean = np.nanmean(raw_data, axis=0)

temporary_fill= np.nanmax(raw_data) + 1


temporary_stats = np.array([np.nanmin(raw_data, axis=0), temporary_mean, np.nanmax(raw_data, axis=0)])

temporary_stats

/tmp/ipykernel_3906871/2718681720.py:1: RuntimeWarning: Mean of empty slice
  temporary_mean = np.nanmean(raw_data, axis=0)
/tmp/ipykernel_3906871/2718681720.py:6: RuntimeWarning: All-NaN slice encountered
  temporary_stats = np.array([np.nanmin(raw_data, axis=0), temporary_mean, np.nanmax(raw_data, axis=0)])


array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

# Splitting 

In [142]:
columns_string = np.argwhere(np.isnan(temporary_mean)).squeeze()
columns_string

array([ 1,  3,  5,  8,  9, 10, 11, 12])

In [143]:
columns_numeric = np.argwhere(np.isnan(temporary_mean)==False).squeeze()
columns_numeric

array([ 0,  2,  4,  6,  7, 13])

# Re-importing data seprately

In [144]:
loan_string_data = np.genfromtxt('data/loan-data.csv', delimiter=";", skip_header=1, 
                            usecols=columns_string, encoding="cp855", dtype=np.str_)
loan_string_data

array([['May-15', 'Current', ' 36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', ' 36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', ' 36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [145]:
loan_numeric_data = np.genfromtxt('data/loan-data.csv', delimiter=";", skip_header=1, 
                            usecols=columns_numeric, encoding="cp855", filling_values=temporary_fill)
loan_numeric_data

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

# Rename columns

In [146]:
full_header = np.genfromtxt('data/loan-data.csv', delimiter=";", skip_footer=raw_data.shape[0], 
                            encoding="cp855", dtype=np.str_)
full_header

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [147]:
string_headers, numeric_headers = full_header[columns_string], full_header[columns_numeric]
    

In [148]:
string_headers

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [149]:
numeric_headers

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

# Creating checkpoint

In [150]:
def check_point(filename, checkpoint_header, checkpoint_data):
    np.savez(file=filename, header=checkpoint_header, data=checkpoint_data)
    variable_checkpoint = np.load("{}.npz".format(filename))
    return (variable_checkpoint)

In [151]:
check_point_test = check_point('loan_string_data', string_headers, loan_string_data)

In [152]:
check_point_test['data']

array([['May-15', 'Current', ' 36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', ' 36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', ' 36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

# Manipulation String Columns

In [153]:
string_headers

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [154]:
string_headers[0] = 'issue_date'

### Issue data

In [155]:
np.unique(loan_string_data[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [156]:
loan_string_data[:,0] = np.chararray.strip(loan_string_data[:, 0], '-15')
loan_string_data[:,0]

array(['May', '', 'Sep', ..., 'Jun', 'Apr', 'Dec'], dtype='<U69')

In [157]:
months = np.array(['', 'Jan', 'Feb', 'Mar', "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"])

In [158]:
for i in range(13):
    loan_string_data[:,0] = np.where(loan_string_data[:,0]==months[i],i, loan_string_data[:,0])
    
loan_string_data[:, 0]    

array(['5', '0', '9', ..., '6', '4', '12'], dtype='<U69')

### Loan Status

In [159]:
np.unique(loan_string_data[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [160]:
bad_status = np.array(['Charged Off', "Default", "Late (31-120 days)"])

In [161]:
loan_string_data[:,1] = np.where(np.isin(loan_string_data[:,1], bad_status), 0, 1)

In [162]:
np.unique(loan_string_data[:, 1])

array(['0', '1'], dtype='<U69')

### Terms 

In [163]:
string_headers

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [164]:
string_headers[2] = "terms months"

In [165]:
np.unique(loan_string_data[:,2])

array(['', ' 36 months', ' 60 months'], dtype='<U69')

In [166]:
loan_string_data[:,2] = np.chararray.strip(loan_string_data[:,2], " months ")
loan_string_data[:, 2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [167]:
loan_string_data[:,2] = np.where(loan_string_data[:,2]=='', '60', loan_string_data[:,2])

In [168]:
loan_string_data[:, 2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

### Grade and Sub-Grade

In [169]:
string_headers

array(['issue_date', 'loan_status', 'terms months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [170]:
np.unique(loan_string_data[:, 3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [171]:
np.unique(loan_string_data[:, 4], return_counts=True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([514, 285, 278, 239, 323, 502, 509, 517, 530, 553, 494, 629, 567, 586, 564, 423, 391, 267,
        250, 255, 223, 235, 162, 171, 139, 114,  94,  52,  34,  43,  16,  19,  10,   3,   7,   2]))

 ### Filling Subgrade

In [172]:
for i in np.unique(loan_string_data[:, 3])[1:]:
    loan_string_data[:,4] = np.where((loan_string_data[:, 4]=='') & (loan_string_data[:,3]==i), i + "5",
                                    loan_string_data[:, 4])
np.unique(loan_string_data[:,4], return_counts=True) 

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5]))

In [173]:
loan_string_data[:,4] = np.where(loan_string_data[:, 4]=='', "H1",
                                    loan_string_data[:, 4])
np.unique(loan_string_data[:,4], return_counts=True) 

(array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
        'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
        'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69'),
 array([285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267, 250,
        255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5,   9]))

### Removing grade columns

In [174]:
loan_string_data = np.delete(loan_string_data, 3, axis=1)

In [175]:
loan_string_data[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [176]:
string_headers = np.delete(string_headers, 3)
string_headers[3]

'sub_grade'

### Converting sub-grade to number

In [177]:
np.unique(loan_string_data[:, 3], return_counts=True)

(array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
        'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
        'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69'),
 array([285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267, 250,
        255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5,   9]))

In [178]:
keys = list(np.unique(loan_string_data[:, 3]))
values = list(range(1, np.unique(loan_string_data[:, 3]).shape[0] + 1))
dict_sub_grade = dict(zip(keys, values))

In [179]:
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [180]:
for i in keys:
    loan_string_data[:,3] = np.where(loan_string_data[:, 3]==i, dict_sub_grade[i], loan_string_data[:,3])

loan_string_data[:, 3]    

array(['13', '5', '10', ..., '5', '17', '4'], dtype='<U69')

### Verification Status

In [181]:
string_headers

array(['issue_date', 'loan_status', 'terms months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [184]:
np.unique(loan_string_data[:, 4])

array(['0', '1'], dtype='<U69')

In [183]:
bad_status_verified = np.array(['', 'Not Verified'])

loan_string_data[:,4] = np.where(np.isin(loan_string_data[:,4] , bad_status_verified), 0, 1)
loan_string_data[:,4]

array(['1', '1', '1', ..., '1', '1', '0'], dtype='<U69')

### Url 

In [185]:
string_headers

array(['issue_date', 'loan_status', 'terms months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [186]:
loan_string_data[:, 5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [187]:
loan_string_data[:,5] = np.chararray.strip(loan_string_data[:, 5], 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

In [188]:
loan_string_data[:, 5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [194]:
loan_numeric_data[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [197]:
np.array_equal(loan_string_data[:, 5].astype(dtype=np.int32), loan_numeric_data[:, 0].astype(dtype=np.int32))

True

In [206]:
loan_string_data = np.delete(loan_string_data, 5, axis=1)

In [204]:
string_headers = np.delete(string_headers, 5)

### Address state

In [205]:
string_headers[5]

'addr_state'

In [207]:
string_headers[5] = "state address"

In [214]:
state_name, state_counts = np.unique(loan_string_data[:,5], return_counts=True)
state_name, state_counts


(array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
        'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
        'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
        'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69'),
 array([ 500,   26,  119,   74,  220, 1336,  201,  143,   27,   27,  690,  321,   44,  389,  152,
          84,   84,  116,  210,  222,   10,  267,  156,  160,   61,   28,  261,   16,   25,   58,
         341,   57,  130,  777,  312,   83,  108,  320,   40,  107,   24,  143,  758,   74,  242,
          17,  216,  148,   49,   27]))

In [215]:
state_counts_sorted = np.argsort(-state_counts)
state_counts_sorted

array([ 5, 33, 42, 10,  0, 13, 30, 11, 37, 34, 21, 26, 44, 19,  4, 46, 18,  6, 23, 22, 14, 47,  7,
       41, 32,  2, 17, 36, 39, 16, 15, 35, 43,  3, 24, 29, 31, 48, 12, 38, 25,  9,  8, 49,  1, 28,
       40, 45, 27, 20])

In [217]:
state_name[state_counts_sorted], state_counts[state_counts_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10]))

In [219]:
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [220]:
loan_string_data[:, 5] = np.where(loan_string_data[:,5]=='', 0, loan_string_data[:,5])

In [223]:
loan_string_data[:, 5] = np.where(np.isin(loan_string_data[:,5], states_west), 1, loan_string_data[:,5])
loan_string_data[:, 5] = np.where(np.isin(loan_string_data[:,5], states_south), 2, loan_string_data[:,5])
loan_string_data[:, 5] = np.where(np.isin(loan_string_data[:,5], states_midwest), 3, loan_string_data[:,5])
loan_string_data[:, 5] = np.where(np.isin(loan_string_data[:,5], states_east), 4, loan_string_data[:,5])

In [224]:
np.unique(loan_string_data[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

## Converting string data to number

In [225]:
loan_string_data

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [227]:
loan_string_data = loan_string_data.astype(int)

In [228]:
loan_string_data 

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

## Checkpoint 1: string

In [229]:
checkpoint_string = check_point("Checkpoint_String", string_headers, loan_string_data)

In [230]:
checkpoint_string

In [231]:
checkpoint_string['data']

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [232]:
checkpoint_string['header']

array(['issue_date', 'loan_status', 'terms months', 'sub_grade', 'verification_status',
       'state address'], dtype='<U19')

In [234]:
np.array_equal(checkpoint_string["data"], loan_string_data)

True

# Manipulating numeric data

In [235]:
numeric_headers

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [237]:
loan_numeric_data

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [239]:
loan_numeric_data[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [241]:
temporary_fill

68616520.0

In [242]:
np.isin(temporary_fill, loan_numeric_data[:,0])

array(False)

In [243]:
temporary_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [248]:
temporary_stats[:,columns_numeric]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

In [246]:
loan_numeric_data[:, 2 ]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [249]:
loan_numeric_data[:, 2] = np.where(loan_numeric_data[:, 2]==temporary_fill, 
                                   temporary_stats[0, columns_numeric[2]], loan_numeric_data[:,2])

In [250]:
loan_numeric_data[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [253]:
for i in [1, 3,4,5]:
    loan_numeric_data[:,i] = np.where(loan_numeric_data[:, i]==temporary_fill, 
                                      temporary_stats[2, columns_numeric[i]], loan_numeric_data[:, i])

loan_numeric_data    

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

In [254]:
np.isin(temporary_fill, loan_numeric_data)

array(False)

In [255]:
numeric_headers

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [256]:
checkpoint_string['header']

array(['issue_date', 'loan_status', 'terms months', 'sub_grade', 'verification_status',
       'state address'], dtype='<U19')

# Exchange rate

In [267]:
EUR_USD = np.genfromtxt('data/EUR-USD.csv', delimiter=',', skip_header=1, usecols=3)

In [268]:
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [269]:
loan_string_data[:,0]

array([ 5,  0,  9, ...,  6,  4, 12])

In [282]:
exchange_rate = loan_string_data[:, 0]
for i in range(1, 13):
    exchange_rate = np.where(exchange_rate==i, EUR_USD[i-1], exchange_rate)
    
exchange_rate = np.where(exchange_rate==0, np.mean(EUR_USD), exchange_rate)    
    
exchange_rate    

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [283]:
exchange_rate.shape

(10000,)

In [278]:
loan_string_data.shape

(10000, 6)

In [285]:
exchange_rate = np.reshape(exchange_rate, (10000, 1))

In [286]:
loan_numeric_data

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

In [295]:
loan_numeric_data = np.hstack((loan_numeric_data, exchange_rate))

In [289]:
numeric_headers

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [296]:
numeric_headers = np.concatenate((numeric_headers, np.array(["exchange_rate"])), axis=None)

# Convert Dollar to Euro

In [298]:
dollar_columns = [1, 2, 4, 5]

In [305]:
for i in dollar_columns:
    loan_numeric_data = np.hstack((loan_numeric_data, np.reshape(loan_numeric_data[:, i]/loan_numeric_data[:,6], (10000, 1))))

In [306]:
loan_numeric_data

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

# Expending headers

In [310]:
additionnal_headers = np.array(["{}_EUR".format(head) for head in numeric_headers[dollar_columns]])

In [311]:
numeric_headers  = np.concatenate((numeric_headers, additionnal_headers))

In [312]:
numeric_headers

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [313]:
numeric_headers[dollar_columns] = np.array(["{}_USD".format(head) for head in numeric_headers[dollar_columns]])

In [314]:
numeric_headers

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [315]:
columns_index_order = [0, 1,7,2,8,3,4,9,5,10,6]

In [317]:
numeric_headers = numeric_headers[columns_index_order]

In [318]:
numeric_headers

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [324]:
loan_numeric_data = loan_numeric_data[:, columns_index_order]

In [325]:
loan_numeric_data

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,    31933.3 ,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,    27132.46,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,    13326.3 ,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     8910.3 ,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,    31490.9 ,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,     9145.8 ,        1.09]])

# Interest rate 

In [326]:
loan_numeric_data[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [328]:
loan_numeric_data[:,5] = loan_numeric_data[:, 5]/100

In [329]:
loan_numeric_data[:, 5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

# checkpoint Numeric

In [330]:
checkpoint_numeric = check_point("check-Numeric", numeric_headers, loan_numeric_data)

In [331]:
checkpoint_numeric['header'], checkpoint_numeric['data']

(array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
        'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
       dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,    31933.3 ,        1.1 ],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,    27132.46,        1.11],
        [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,    13326.3 ,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     8910.3 ,        1.12],
        [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,    31490.9 ,        1.11],
        [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,     9145.8 ,        1.09]]))

# Complete DataSet

In [332]:
checkpoint_string['data'].shape

(10000, 6)

In [333]:
checkpoint_numeric['data'].shape

(10000, 11)

In [336]:
loan_data = np.hstack((checkpoint_numeric['data'], checkpoint_string['data']))

In [337]:
loan_data

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [339]:
loan_full_headers = np.concatenate((checkpoint_numeric['header'], checkpoint_string['header']))

In [340]:
loan_full_headers

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate',
       'issue_date', 'loan_status', 'terms months', 'sub_grade', 'verification_status',
       'state address'], dtype='<U19')

# Sort the new data

In [344]:
loan_data = loan_data[np.argsort(loan_data[:,0])]

In [345]:
np.argsort(loan_data[:, 0])

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [346]:
loan_data

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

# Merging data 

In [352]:
loan_data = np.vstack((loan_full_headers, loan_data))

In [353]:
loan_data 

array([['id', 'loan_amnt_USD', 'loan_amnt_EUR', ..., 'sub_grade', 'verification_status',
        'state address'],
       ['id', 'loan_amnt_USD', 'loan_amnt_EUR', ..., 'sub_grade', 'verification_status',
        'state address'],
       ['373332.0', '9950.0', '9038.082814338286', ..., '21.0', '0.0', '1.0'],
       ...,
       ['68614880.0', '5600.0', '5121.647851612413', ..., '8.0', '1.0', '1.0'],
       ['68615915.0', '4000.0', '3658.319894008867', ..., '10.0', '1.0', '2.0'],
       ['68616519.0', '21600.0', '19754.927427647883', ..., '3.0', '0.0', '2.0']], dtype='<U32')

In [354]:
np.savetxt("loan-data-preprocessed.csv",
           loan_data,
           delimiter=',',
           fmt="%s")