In [11]:
import numpy as np
import pandas as pd
from numpy.random import shuffle
from numpy.random import Generator as gen 
from numpy.random import PCG64 as pcg


In [16]:
np.set_printoptions(suppress=True, linewidth=100, precision=2)

# Importing data

In [23]:
raw_data = np.genfromtxt('data/loan-data.csv', delimiter=";", skip_header = 1, autostrip = True, encoding = "cp855")
raw_data

# Checking data

In [24]:
np.isnan(raw_data).sum()

88005

In [43]:
temporary_mean = np.nanmean(raw_data, axis=0)

temporary_fill= np.nanmax(raw_data) + 1


temporary_stats = np.array([np.nanmin(raw_data, axis=0), temporary_mean, np.nanmax(raw_data, axis=0)])

temporary_stats

/tmp/ipykernel_1450604/2718681720.py:1: RuntimeWarning: Mean of empty slice
  temporary_mean = np.nanmean(raw_data, axis=0)
/tmp/ipykernel_1450604/2718681720.py:6: RuntimeWarning: All-NaN slice encountered
  temporary_stats = np.array([np.nanmin(raw_data, axis=0), temporary_mean, np.nanmax(raw_data, axis=0)])


array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

# Splitting 

In [42]:
columns_string = np.argwhere(np.isnan(temporary_mean)).squeeze()
columns_string

array([ 1,  3,  5,  8,  9, 10, 11, 12])

In [39]:
columns_numeric = np.argwhere(np.isnan(mean)==False).squeeze()
columns_numeric

array([ 0,  2,  4,  6,  7, 13])

# Re-importing data seprately

In [112]:
loan_string_data = np.genfromtxt('data/loan-data.csv', delimiter=";", skip_header=1, 
                            usecols=columns_string, encoding="cp855", dtype=np.str_)
loan_string_data

array([['May-15', 'Current', ' 36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', ' 36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', ' 36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [66]:
loan_numeric_data = np.genfromtxt('data/loan-data.csv', delimiter=";", skip_header=1, 
                            usecols=columns_numeric, encoding="cp855", filling_values=temporary_fill)
numeric_data

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

# Rename columns

In [54]:
full_header = np.genfromtxt('data/loan-data.csv', delimiter=";", skip_footer=raw_data.shape[0], 
                            encoding="cp855", dtype=np.str_)
full_header

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [59]:
string_headers, numeric_headers = full_header[columns_string], full_header[columns_numeric]
    

In [61]:
string_headers

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [62]:
numeric_headers

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

# Creating checkpoint

In [64]:
def check_point(filename, checkpoint_header, checkpoint_data):
    np.savez(file=filename, header=checkpoint_header, data=checkpoint_data)
    variable_checkpoint = np.load("{}.npz".format(filename))
    return (variable_checkpoint)

In [67]:
check_point_test = check_point('loan_string_data', string_headers, loan_string_data)

In [77]:
check_point_test['data']

array([['May-15', 'Current', ' 36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', ' 36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', ' 36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

# Manipulation String Columns

In [78]:
string_headers

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [79]:
string_data[0] = 'issue_date'

### Issue data

In [93]:
np.unique(loan_string_data[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [94]:
loan_string_data[:,0] = np.chararray.strip(loan_string_data[:, 0], '-15')
loan_string_data[:,0]

array(['May', '', 'Sep', ..., 'Jun', 'Apr', 'Dec'], dtype='<U69')

In [87]:
months = np.array(['', 'Jan', 'Feb', 'Mar', "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"])

In [98]:
for i in range(13):
    loan_string_data[:,0] = np.where(loan_string_data[:,0]==months[i],i, loan_string_data[:,0])
    
loan_string_data[:, 0]    

array(['5', '0', '9', ..., '6', '4', '12'], dtype='<U69')

### Loan Status

In [117]:
np.unique(loan_string_data[:,1])

array(['0', '1'], dtype='<U69')

In [114]:
bad_status = np.array(['Charged Off', "Default", "Late (31-120 days)"])

In [115]:
loan_string_data[:,1] = np.where(np.isin(loan_string_data[:,1], bad_status), 0, 1)

In [116]:
loan_string_data[:, 1]

array(['1', '1', '1', ..., '1', '1', '1'], dtype='<U69')

### Terms 

In [119]:
string_headers

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [136]:
string_headers[2] = "terms months"

In [133]:
np.unique(loan_string_data[:,2])

array(['36', '60'], dtype='<U69')

In [134]:
loan_string_data[:,2] = np.chararray.strip(loan_string_data[:,2], " months ")
loan_string_data[:, 2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [128]:
loan_string_data[:,2] = np.where(loan_string_data[:,2]=='', '60', loan_string_data[:,2])

In [135]:
loan_string_data[:, 2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')