# NumPy DataTypes

In [3]:
import numpy as np

### 1. With the help of the <i> np.array() </i>function, create a 1-D array variable <i> array_hw_1 </i> with the numbers from 1 to 8 and display it on the screen.

In [4]:
array_hw_1 = np.array([[1,2,3,4,5,6,7,8]])

### 2.Check its type, shape and size. 
<i> (<b>Hint </b>: "type" is a Python function, while "shape" and "size" are attributes of the array) </i>

In [6]:
print(type(array_hw_1))
print((array_hw_1.shape))
array_hw_1.size

<class 'numpy.ndarray'>
(1, 8)


8

### 3. Now, create a 2x4 2-D array, <i> array_hw_2</i> with the same values & display it on screen. 

In [7]:
array_hw_2 = np.array([[1,2,3,4], [5,6,7,8]])
array_hw_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### 4. Find its type, shape, and size. 

In [8]:
print(type(array_hw_2))
print((array_hw_2.shape))
array_hw_2.size

<class 'numpy.ndarray'>
(2, 4)


8

### 5. Use square brackets to create a 3-D array with the same values as <i> array_hw_2 </i> and display it on screen.

In [10]:
array_hw_3 = np.array([[[1,2, 3, 4], [4,5,6,7]]])
array_hw_3

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]]])

### 6. Find its type, shape and size. 


In [11]:
print(type(array_hw_3))
print((array_hw_3.shape))
array_hw_3.size

<class 'numpy.ndarray'>
(1, 2, 4)


8

### 7. Define a 2-D list <i> list_hw_1 </i> with the same values as <i> array_hw_2 </i>and display it on screen.

In [12]:
list_hw_1 = [[1, 2, 3, 4], [5, 6, 7, 8]]
list_hw_1

[[1, 2, 3, 4], [5, 6, 7, 8]]

### 8. Find the length of this 2-D list. 

In [13]:
len(list_hw_1)

2

### 9. Fint the length of one of its sublists. 

In [14]:
len(list_hw_1[1])

4

### 10. Verify its type. 

In [16]:
print(type(list_hw_1))

<class 'list'>


### 11. Use the <i>np.array()</i> function to create an array out of <i> list_hw_1</i> and display it on screen.

In [17]:
new_array = np.array(list_hw_1)
new_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### 12. Create two more variables and display them on screen:
    A) A list which is the sum of the two sublists of list_hw_1;
    B) An array which is the sum of the two subarrays of array_hw_4;
    
    (Hint: Use indexing to refer to the different sub-lists/arrays)

In [18]:
new_list  = list_hw_1[0] + list_hw_1[1]
new_list

[1, 2, 3, 4, 5, 6, 7, 8]

In [21]:
array_sum = new_array[0] + new_array[1]
array_sum 

array([ 6,  8, 10, 12])

### 13. Find the square roots of all the elements in <i> array_sum </i>
   <i> (<b>Hint</b>: Use the np.sqrt() function)

In [22]:
np.sqrt(array_sum)

array([2.44948974, 2.82842712, 3.16227766, 3.46410162])

### 13. Find the square roots of all the elements in <i> list_sum </i>
   <i> (<b>Hint</b>: Most NumPy functions are equipped to handle <b> lists </b>like ndarrays with the same shape)

In [28]:
print([element**(1/2) for element in new_list])

[1.0, 1.4142135623730951, 1.7320508075688772, 2.0, 2.23606797749979, 2.449489742783178, 2.6457513110645907, 2.8284271247461903]


### 14. Use <i> np.genfromtxt() </i> to import the <i> "Lending-Company-Total-Price.csv" </i> file as strings and display its contents.
    You can open the file in a text editor like Notepad++ to check its delimiter. 

### 15. Use the <i> skip_header </i> and <i> usecols </i> parameters to only take the numerical data from the file. Then, let's see how the inputs change if we alter the datatype argument to:

    A) The default (not specify it)
    B) 32-bit integers (np.int32)
    C) 32-bit floats (np.float32)
    D) 64-bit complex numbers (np.complex64)
    E) Unicode (np.unicode)
    F) Objects (np.object)
    G) None

### 16. Setting the datatype to None means the function automatically chooses the datatype for each column of the text file, so let's see how this works for all the columns.